# Goal
* A generic python package to initialize different crystal structure for simulation
* Output: Elements needed to define a crystal structure
    - Lattice vectors (3x3) or box parameters (lx, ly, lz, xy, xz, yz)
    - Basis vectors (Nx3)
    - Orientation in form of  quaternion (for anisotropic particles, if needed)
* Input: information to define a crystal
    - For basis vector
        - Pearson symbol + (position parameter for some Wyckoff site) 
        - Space group + Wyckoff site positions(unique representation)
        - if needed: orientation
    - For Lattice vector:
        - Standard: a, b/a, a/c, 𝜶, 𝜷, 𝜸
        - Can be reduced based on Pearson symbol or Space group
    - complete information: space group + (a, b/a, a/c, 𝜶, 𝜷, 𝜸) + unique Wyckoff positions


# Existing crystal database referenced:

http://aflowlib.org/CrystalDatabase/:

This database provides 590 different known crystal structures in nature. This package allows user to directly form the 590 structures listed as numpy arrays and provide easy access to change the free parameters within each structure prototype to get user defined structures derived from these prototypes.

* M. J. Mehl, D. Hicks, C. Toher, O. Levy, R. M. Hanson, G. L. W. Hart, and S. Curtarolo, The AFLOW Library of Crystallographic Prototypes: Part 1, Comp. Mat. Sci. 136, S1-S828 (2017). (doi=10.1016/j.commatsci.2017.01.017))

* D. Hicks, M. J. Mehl, E. Gossett, C. Toher, O. Levy, R. M. Hanson, G. L. W. Hart, and S. Curtarolo, The AFLOW Library of Crystallographic Prototypes: Part 2, Comp. Mat. Sci. 161, S1-S1011 (2019). (doi=10.1016/j.commatsci.2018.10.043)




# What it can do now:

- Generate crystal structure by Aflow Prototypes or fully defined structure by spacegroup and Wyckoff positions
- Provide easy to allow creation of new structures with user defined parameters
- Some basic crystal structure related methods: space group symetry operation, box parameter conversion, etc


# Installation

`$ pip install fedorov`

# Demo with Aflow Prototypes

In [1]:
import numpy as np
from fedorov import convert_to_box
from fedorov import SpaceGroup, Prototype, AflowPrototype

In [2]:
# generate the exact prototype provided by Aflow, use prototype_index [0, 589]
prototype_index = 5
new_structure = AflowPrototype(prototype_index=prototype_index, print_info=False, 
                               set_type=True)
basis_vectors, type_list = new_structure.get_basis_vectors()
lattice_vectors = new_structure.get_lattice_vectors()
Lx, Ly, Lz, xy, xz, yz = convert_to_box(lattice_vectors)
print(basis_vectors, '\n', lattice_vectors, '\n',type_list, '\n', 
      Lx, Ly, Lz, xy, xz, yz, '\n')

[[0.     0.     0.    ]
 [0.5    0.5    0.8973]
 [0.5    0.5    0.4517]
 [0.5    0.     0.3785]
 [0.     0.5    0.3785]] 
 [[4.046  0.     0.    ]
 [0.     4.046  0.    ]
 [0.     0.     4.1394]] 
 ['B', 'A', 'C', 'A', 'A'] 
 4.046 4.046 4.13940000000478 0.0 0.0 0.0 



In [3]:
# get free parameter info when initializing using print_info=True
# then modify to get user defined structures based on the prototype:
prototype_index = 5
new_structure = AflowPrototype(prototype_index=prototype_index, print_info=True, 
                               set_type=True)

Info for the chosen crystal structure prototype:
 id: tP5-O3Pb(Ti0.48)Zr0.52-99, (Pearson-Chemistry-SpaceGroup)
 Wyckoff sites: ['bc', 'a', 'b']
 available lattice parameters: {'a': 4.046, 'c': 4.13940000000478}
 available basis parameters: {'z1': 0.0, 'z2': 0.8973, 'z3': 0.4517, 'z4': 0.3785}


In [4]:
basis_vectors, type_list = new_structure.get_basis_vectors(z1=0.1)
lattice_vectors = new_structure.get_lattice_vectors(a=3)
Lx, Ly, Lz, xy, xz, yz = convert_to_box(lattice_vectors)
print(basis_vectors, '\n', lattice_vectors, '\n',type_list, '\n', 
      Lx, Ly, Lz, xy, xz, yz, '\n')

[[0.     0.     0.1   ]
 [0.5    0.5    0.8973]
 [0.5    0.5    0.4517]
 [0.5    0.     0.3785]
 [0.     0.5    0.3785]] 
 [[3.     0.     0.    ]
 [0.     3.     0.    ]
 [0.     0.     4.1394]] 
 ['B', 'A', 'C', 'A', 'A'] 
 3.0 3.0 4.13940000000478 0.0 0.0 0.0 



# Demo with space group and Wyckoff postions

In [5]:
# generate crystal structure by spacegroup number and Wyckoff site
new_structure_by_spg = SpaceGroup(220)
basis_positions = np.array([[0.1, 0.12, 0.13], [0.14, 0.15, 0.17]])
base_quaternions = np.array([[0, 0, 0, 0], [0.1, 0.1, 0.1, 0.1]])

basis_vectors, type_list, quaternions = \
    new_structure_by_spg.get_basis_vectors(basis_positions, base_type=['A', 'B'], 
                                           base_quaternions=base_quaternions, 
                                           apply_orientation=True)
lattice_vectors = new_structure_by_spg.get_lattice_vectors()


# Demo with Prototype (Spacegroup and minimal Wyckoff position parameters)


In [6]:
# define a prototype by spacegroup number and wyckoff site names
structure_test = Prototype(space_group_number=230, wyckoff_site='hh', type_by_site='ab', 
                           print_info=True)

Space group number: 230
 lattice type: cubic
 Default parameters for lattice: {'a': 1}
Wyckoff sites:['h', 'h']
 Particle type for each Wyckoff sites:['A', 'B']
 lattice parameters list:['a']
 basis parameters list:['x1', 'y1', 'z1', 'x2', 'y2', 'z2']


In [7]:
basis_params = {'x1': 0.12, 'y1': 0.13, 'z1': 0.14, 'x2': -0.125, 'y2': -0.135, 'z2': -0.145}
basis_vectors, type_list = structure_test.get_basis_vectors(**basis_params)
lattice_vectors = structure_test.get_lattice_vectors(a=4)

# print(basis_vectors, '\n', lattice_vectors, '\n',type_list, '\n')

# Features to add?
* Possible useful functions:
    - different density scaling
    - box replication in different directions
    - support for gsd file format for initial frame